// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialBackend.Models;

namespace SocialBackend.Migrations
{
    [DbContext(typeof(SocialBackendContext))]
    partial class SocialBackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SocialBackend.Models.Todo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Userid");

                    b.Property<bool>("complete");

                    b.Property<DateTime>("dueDate");

                    b.Property<string>("task");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("SocialBackend.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("authToken");

                    b.Property<string>("emailAddress");

                    b.Property<bool>("online");

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SocialBackend.Models.Todo", b =>
                {
                    b.HasOne("SocialBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid");
                });
#pragma warning restore 612, 618
        }
    }
}
